## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則話來觀察訓練情形。

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score

# Wine 
alpha  = 0.1
### lasso

wine = datasets.load_wine()

In [5]:
x_train, x_test, y_train, y_test = train_test_split(wine.data, 
                                                    wine.target, 
                                                    test_size=0.1, 
                                                    random_state=4)


In [22]:
lasso = linear_model.Lasso(alpha =0.1)

In [23]:
lasso.fit(x_train, y_train)

Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [24]:
y_pred = lasso.predict(x_test)

In [25]:
lasso.coef_

array([-0.        ,  0.        , -0.        ,  0.02903446,  0.00036735,
       -0.        , -0.29879073,  0.        , -0.        ,  0.09727668,
       -0.        , -0.        , -0.00123357])

In [28]:
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 0.11


# Wine 
alpha  = 1

In [30]:
lasso = linear_model.Lasso(alpha =1)

In [31]:
lasso.fit(x_train, y_train)

Lasso(alpha=1, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [32]:
y_pred = lasso.predict(x_test)

In [33]:
lasso.coef_

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
       -0.        , -0.        ,  0.        , -0.        ,  0.        ,
       -0.        , -0.        , -0.00158746])

In [34]:
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 0.37


# Boston
lasso

In [50]:
boston = datasets.load_boston()

In [51]:
x_train, x_test, y_train, y_test = train_test_split(boston.data, 
                                                    boston.target, 
                                                    test_size=0.1, 
                                                    random_state=4)


In [52]:
lasso = linear_model.Lasso(alpha =0.1)

In [53]:
lasso.fit(x_train, y_train)

Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [54]:
y_pred = lasso.predict(x_test)

In [55]:
lasso.coef_

array([-0.11567831,  0.05152311, -0.03346275,  1.2230427 , -0.        ,
        3.53216363, -0.00922692, -1.19460642,  0.28775344, -0.01473748,
       -0.75732817,  0.01037228, -0.58007751])

In [56]:
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 18.19


In [57]:
lasso = linear_model.Lasso(alpha =1)
lasso.fit(x_train, y_train)
y_pred = lasso.predict(x_test)
lasso.coef_

array([-0.07256057,  0.04967103, -0.        ,  0.        , -0.        ,
        0.80886056,  0.02328171, -0.68444051,  0.26862528, -0.01526566,
       -0.71692899,  0.00828412, -0.77123108])

In [58]:
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 23.24


# Wine
### Ridge

In [59]:
x_train, x_test, y_train, y_test = train_test_split(wine.data, 
                                                    wine.target, 
                                                    test_size=0.1, 
                                                    random_state=4)


In [60]:
ridge = linear_model.Ridge(alpha=1.0)

In [61]:
ridge.fit(x_train, y_train)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [64]:
y_pred = ridge.predict(x_test)

In [65]:
print(ridge.coef_)

[-1.02585859e-01  3.04760174e-02 -1.72984304e-01  4.20252277e-02
  3.29809025e-04  1.22527858e-01 -3.52268478e-01 -1.43905193e-01
  3.86108428e-02  7.68595958e-02 -1.38667607e-01 -2.52968701e-01
 -7.60006286e-04]


In [66]:
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 0.07


In [88]:
ridge = linear_model.Ridge(alpha=0.1)

In [89]:
ridge.fit(x_train, y_train)
y_pred = ridge.predict(x_test)

In [90]:
print(ridge.coef_)

[-1.04747678e-01  2.93000101e-02 -1.78367204e-01  4.30426463e-02
  1.41525650e-04  1.46625147e-01 -3.68355272e-01 -2.40726939e-01
  4.17957485e-02  7.48587578e-02 -1.56797641e-01 -2.63031694e-01
 -7.45368953e-04]


In [91]:
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 0.07


# Boston
### ridge

In [92]:
x_train, x_test, y_train, y_test = train_test_split(boston.data, 
                                                    boston.target, 
                                                    test_size=0.1, 
                                                    random_state=4)


In [94]:
ridge = linear_model.Ridge(alpha=1.0)

In [95]:
ridge.fit(x_train, y_train)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [96]:
y_pred = ridge.predict(x_test)

In [97]:
print(ridge.coef_)

[-1.22488037e-01  4.95483049e-02 -1.15839833e-02  2.89071820e+00
 -1.00402895e+01  3.66674306e+00 -4.43653915e-03 -1.38990862e+00
  3.02286292e-01 -1.32259798e-02 -8.52141794e-01  9.86708353e-03
 -5.43681130e-01]


In [98]:
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 17.35


In [109]:
ridge = linear_model.Ridge(alpha=100)

In [110]:
ridge.fit(x_train, y_train)

Ridge(alpha=100, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [111]:
y_pred = ridge.predict(x_test)

In [112]:
print(ridge.coef_)

[-0.11766158  0.0562758  -0.04288743  0.65849704 -0.22586049  2.16498362
  0.00322957 -1.15750225  0.32562147 -0.01609718 -0.81687903  0.00954813
 -0.673504  ]


In [113]:
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 19.83
